### ISSUE TITLE
Can we have options for resize?

### ISSUE THREAD

**Issue by Designer023** [kraken-io/gulp-kraken#1]
Currently there is no way to specify resize. Can we get options added? I'd do it myself but I don't really know how, as much as I'll try :smile: 

Ideally if we can pass a size and and prefix so I can optimize and create responsive image options, then that would be perfect:

```
kraken({
      key: 'XXXX',
      secret: 'YYYY',
      lossy: true,
      wait: true,
      resize: {
          width: 100,
          height: 75,
          strategy: 'fit',
          prefix:'mobile-'
      }
})
```

**Comment by wesbos** [comment]
Sort of goes against the gulp mantra of doing one thing and one thing well.

For resizing, check out https://www.npmjs.com/package/gulp-image-resize

**Comment by Designer023** [comment]
Yeah that makes sense. I'll use that :+1:

**Comment by wesbos** [comment]
😎
