### ISSUE TITLE
Does not skip previously optimized files

### ISSUE THREAD

**Issue by wturnerharris** [kraken-io/gulp-kraken#3]
I realize there is a concurrency option, but the task does not properly skip and move on to other images in the queue. Each time I run `gulp kraken` task I have created following the documentation, it only processes the first 16 images and does not track or follow up with details after those even though there are well-beyond 16 images that need processing.

**Comment by phbou72** [comment]
I had the same problem too. It's related to gulp actually. You need to return the stream to make it work correctly. Look at the second line.

```
gulp.task('kraken', function () {
    return gulp.src('images/**/*.*')
        .pipe(kraken({
            key: 'kraken-api-key-here',
            secret: 'kraken-api-secret-here',
            lossy: true,
            concurrency: 6
        }));
});
```

**Comment by wturnerharris** [comment]
@phbou72 - that did it for me. Should have tried that first. Thanks!
